### ISSUE TITLE
Fix typo in documentation

### ISSUE THREAD

**Issue by initmn** [iamstevendao/vue-suggestion#10]
Missing `this`

`inputChange (text) {
      // your search method
      this.items = items.filter(item => item.name.contains(text));
      // now `items` will be showed in the suggestion list
    },`

Must be:

`inputChange (text) {
      // your search method
      this.items = this.items.filter(item => item.name.contains(text));
      // now `items` will be showed in the suggestion list
    },`

**Comment by iamstevendao** [comment]
Thank you!
