### ISSUE TITLE
Type check failed for prop "minLen"

### ISSUE THREAD

**Issue by eugeene** [iamstevendao/vue-suggestion#15]
When I use minLen or maxLen, I get this message:

**vue.js:634 [Vue warn]: Invalid prop: type check failed for prop "minLen". Expected Number with value 5, got String with value "5".**

```

Vue.component("frm-product-suggest", {
    template: `
    <span class="inp__fix">
        <input type="hidden" name="product_id" :value="id" required>
        <vue-suggestion 
            inputClasses="inp__text"
            placeholder="Napište model, nebo značku zboží"
            v-model="product" 
            minLen=5
            :itemTemplate="tpl"
            :items="searchResult" 
            :setLabel="setLabel"
            @changed="onSearch" 
            @selected="onSelected">
        </vue-suggestion>
    </span>`
})
```

Any ideas? Thanx!

**Comment by eugeene** [comment]
when i use **:minLen=5** it works, but **@changed** is called every time the input changes, so I have to check the input parameter for length.

**Comment by iamstevendao** [comment]
@eugeene Sorry I don't understand what you meant by this part: 
> when i use :minLen=5 it works, but @Changed is called every time the input changes, so I have to check the input parameter for length.

**Comment by iamstevendao** [comment]
@eugeene to pass a number you need to use `:minLen="5"`
