### ISSUE TITLE
Can i matching "input" and "label" using "for=" and "id=" ?

### ISSUE THREAD

**Issue by es5es5** [iamstevendao/vue-suggestion#35]
Can i matching <VueSuggestion /> and <label> for focusing input tag.
like the example below.

![image](https://user-images.githubusercontent.com/24954436/193750609-44364d25-e8b7-4e4c-a34c-203982842174.png)

Check it please !

**Comment by iamstevendao** [comment]
you can set `inputOptions.id` from [v2.1.0](https://github.com/iamstevendao/vue-suggestion/releases/tag/v2.1.0)

**Comment by es5es5** [comment]
Thank you!
