### ISSUE TITLE
Is it possible to display items on focus?

### ISSUE THREAD

**Issue by BechirAhmed** [iamstevendao/vue-suggestion#4]
Hi, thanks for this great work.
I'm wondering if it's possible to display all items on focus, id yes how?

**Comment by rusikf** [comment]
Does this issue fixed? I also interested - how to show whole list on focus?(without typing any text) Looks, that text is required when min length >0 to show dropdown https://github.com/iamstevendao/vue-suggestion/blob/master/src/components/vue-suggestion.vue#L193

**Comment by BechirAhmed** [comment]
Try using ```:minLen="0"``` , it works for me

**Comment by rusikf** [comment]
Amazing, it works!! :sunglasses: 
May be add it to readme ? minLen exists in README, but it is not obvious for newbier @iamstevendao
