### ISSUE TITLE
Select suggestion after clicking

### ISSUE THREAD

**Issue by pitonoved** [iamstevendao/vue-suggestion#6]
First of all, thanks for this - it is very useful for me!

Question: as I understand it, the suggestion is selected only after pressing "enter". How can I select a suggestion after clicking on it? Thanks in advance!

**Comment by iamstevendao** [comment]
@pitonoved Glad you find it's useful :) pressing Enter and clicking should have the same behaviour, How can I reproduce your issue?

**Comment by pitonoved** [comment]
I apologize. Apparently I'm just stupid. I rebooted the server - everything works fine. I close issue
